-- CreateTable
CREATE TABLE "Match" (
    "id" INTEGER NOT NULL,
    "referee" TEXT,
    "timezone" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "timestamp" INTEGER NOT NULL,
    "periodsFirst" INTEGER,
    "periodsSecond" INTEGER,
    "venueId" INTEGER,
    "venueName" TEXT,
    "venueCity" TEXT,
    "statusLong" TEXT NOT NULL,
    "statusShort" TEXT NOT NULL,
    "statusElapsed" INTEGER,
    "statusExtra" INTEGER,
    "leagueId" INTEGER NOT NULL,
    "leagueName" TEXT NOT NULL,
    "leagueCountry" TEXT NOT NULL,
    "leagueLogo" TEXT NOT NULL,
    "leagueSeason" INTEGER NOT NULL,
    "round" TEXT NOT NULL,
    "homeTeamId" INTEGER NOT NULL,
    "homeTeamName" TEXT NOT NULL,
    "homeTeamLogo" TEXT NOT NULL,
    "homeTeamWinner" BOOLEAN,
    "awayTeamId" INTEGER NOT NULL,
    "awayTeamName" TEXT NOT NULL,
    "awayTeamLogo" TEXT NOT NULL,
    "awayTeamWinner" BOOLEAN,
    "goalsHome" INTEGER,
    "goalsAway" INTEGER,
    "halftimeHome" INTEGER,
    "halftimeAway" INTEGER,
    "fulltimeHome" INTEGER,
    "fulltimeAway" INTEGER,
    "extratimeHome" INTEGER,
    "extratimeAway" INTEGER,
    "penaltyHome" INTEGER,
    "penaltyAway" INTEGER,

    CONSTRAINT "Match_pkey" PRIMARY KEY ("id")
);
