import { ScheduleSection } from "@/components/features/schedule-section";
import type { ScheduleMatch } from "@/components/widgets/schedule-match-card";

const MATCHES: ScheduleMatch[] = [
	// Live
	{
		id: "s-live-1",
		group: "Group D",
		time: "18:00",
		date: "28/04/26",
		home: { name: "France", flag: "🇫🇷" },
		away: { name: "Netherlands", flag: "🇳🇱" },
		status: "live",
		minute: 63,
		resultHome: 1,
		resultAway: 1,
		bets: [
			{ userId: "u1", name: "kam", betHome: 1, betAway: 1, points: 3 },
			{ userId: "u2", name: "Val", betHome: 2, betAway: 1, points: 2 },
			{ userId: "u4", name: "Sasha", betHome: 1, betAway: 2, points: 2 },
			{ userId: "u6", name: "Max", betHome: 2, betAway: 2, points: 2 },
			{ userId: "u9", name: "Kate", betHome: 1, betAway: 0, points: 2 },
			{ userId: "u5", name: "Dima", betHome: 0, betAway: 0, points: 1 },
			{ userId: "u7", name: "Lena", betHome: 0, betAway: 1, points: 1 },
			{ userId: "u10", name: "Roma", betHome: 2, betAway: 0, points: 1 },
			{ userId: "u8", name: "Igor", betHome: 3, betAway: 1, points: 1 },
			{ userId: "u11", name: "Anya", betHome: 0, betAway: 3, points: 0 },
			{ userId: "u3", name: "valera", betHome: 0, betAway: 2, points: 0 },
		],
	},
	{
		id: "s-live-2",
		group: "Group B",
		time: "21:00",
		date: "28/04/26",
		home: { name: "Spain", flag: "🇪🇸" },
		away: { name: "Croatia", flag: "🇭🇷" },
		status: "live",
		minute: 34,
		resultHome: 3,
		resultAway: 0,
		bets: [
			{ userId: "u4", name: "Sasha", betHome: 3, betAway: 0, points: 3 },
			{ userId: "u2", name: "Val", betHome: 2, betAway: 1, points: 2 },
			{ userId: "u6", name: "Max", betHome: 2, betAway: 0, points: 2 },
			{ userId: "u10", name: "Roma", betHome: 1, betAway: 0, points: 2 },
			{ userId: "u1", name: "kam", betHome: 1, betAway: 1, points: 1 },
			{ userId: "u5", name: "Dima", betHome: 2, betAway: 0, points: 1 },
			{ userId: "u8", name: "Igor", betHome: 4, betAway: 0, points: 1 },
			{ userId: "u11", name: "Anya", betHome: 1, betAway: 0, points: 1 },
			{ userId: "u7", name: "Lena", betHome: 0, betAway: 1, points: 0 },
			{ userId: "u9", name: "Kate", betHome: 1, betAway: 2, points: 0 },
			{ userId: "u3", name: "valera", betHome: 0, betAway: 2, points: 0 },
		],
	},
	// Finished
	{
		id: "s-fin-1",
		group: "Group A",
		time: "18:00",
		date: "28/04/26",
		home: { name: "Germany", flag: "🇩🇪" },
		away: { name: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
		status: "finished",
		resultHome: 2,
		resultAway: 0,
		bets: [
			{ userId: "u2", name: "Val", betHome: 2, betAway: 0, points: 3 },
			{ userId: "u4", name: "Sasha", betHome: 1, betAway: 0, points: 2 },
			{ userId: "u7", name: "Lena", betHome: 3, betAway: 0, points: 2 },
			{ userId: "u9", name: "Kate", betHome: 2, betAway: 1, points: 2 },
			{ userId: "u1", name: "kam", betHome: 1, betAway: 1, points: 1 },
			{ userId: "u5", name: "Dima", betHome: 3, betAway: 1, points: 1 },
			{ userId: "u6", name: "Max", betHome: 1, betAway: 0, points: 1 },
			{ userId: "u10", name: "Roma", betHome: 2, betAway: 2, points: 1 },
			{ userId: "u11", name: "Anya", betHome: 0, betAway: 1, points: 0 },
			{ userId: "u8", name: "Igor", betHome: 0, betAway: 0, points: 0 },
			{ userId: "u3", name: "valera", betHome: 0, betAway: 2, points: 0 },
		],
	},
	{
		id: "s-fin-2",
		group: "Group C",
		time: "21:00",
		date: "28/04/26",
		home: { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
		away: { name: "Denmark", flag: "🇩🇰" },
		status: "finished",
		resultHome: 1,
		resultAway: 2,
		bets: [
			{ userId: "u1", name: "kam", betHome: 1, betAway: 2, points: 3 },
			{ userId: "u5", name: "Dima", betHome: 0, betAway: 2, points: 3 },
			{ userId: "u8", name: "Igor", betHome: 1, betAway: 2, points: 3 },
			{ userId: "u3", name: "valera", betHome: 0, betAway: 1, points: 1 },
			{ userId: "u6", name: "Max", betHome: 0, betAway: 3, points: 1 },
			{ userId: "u11", name: "Anya", betHome: 0, betAway: 2, points: 1 },
			{ userId: "u4", name: "Sasha", betHome: 1, betAway: 1, points: 0 },
			{ userId: "u2", name: "Val", betHome: 2, betAway: 1, points: 0 },
			{ userId: "u7", name: "Lena", betHome: 2, betAway: 0, points: 0 },
			{ userId: "u9", name: "Kate", betHome: 3, betAway: 1, points: 0 },
			{ userId: "u10", name: "Roma", betHome: 1, betAway: 0, points: 0 },
		],
	},
	// Upcoming
	{
		id: "s-1",
		group: "Group A",
		time: "18:00",
		date: "11/06/26",
		home: { name: "Mexico", flag: "🇲🇽" },
		away: { name: "South Africa", flag: "🇿🇦" },
		status: "upcoming",
	},
	{
		id: "s-2",
		group: "Group A",
		time: "21:00",
		date: "11/06/26",
		home: { name: "Korea Republic", flag: "🇰🇷" },
		away: { name: "Czechia", flag: "🇨🇿" },
		status: "upcoming",
	},
	{
		id: "s-3",
		group: "Group B",
		time: "18:00",
		date: "12/06/26",
		home: { name: "Canada", flag: "🇨🇦" },
		away: { name: "Switzerland", flag: "🇨🇭" },
		status: "upcoming",
	},
	{
		id: "s-4",
		group: "Group B",
		time: "21:00",
		date: "12/06/26",
		home: { name: "Bosnia-Herzegovina", flag: "🇧🇦" },
		away: { name: "Qatar", flag: "🇶🇦" },
		status: "upcoming",
	},
	{
		id: "s-5",
		group: "Group C",
		time: "18:00",
		date: "13/06/26",
		home: { name: "Brazil", flag: "🇧🇷" },
		away: { name: "Morocco", flag: "🇲🇦" },
		status: "upcoming",
	},
	{
		id: "s-6",
		group: "Group D",
		time: "21:00",
		date: "13/06/26",
		home: { name: "USA", flag: "🇺🇸" },
		away: { name: "Paraguay", flag: "🇵🇾" },
		status: "upcoming",
	},
];

export default function SchedulePage() {
	return <ScheduleSection matches={MATCHES} />;
}
